source "https://gems.ruby-china.com" # gems.ruby-china.com rubygems.org

# gem 'jekyll-rtd-theme', '~> 2.0', '>= 2.0.10' # gem "jekyll-rtd-theme"

gem "github-pages", group: :jekyll_plugins

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
